---
format_version: 1
pipelines:
  hello-pipeline:
    group: sample-group
    materials:
      - git:  # Ensure this is a list with a dash
          url: 'https://github.com/Vinayaklondhe-hash/GOCD.git'
          branch: main
    stages:
      - name: hello-stage  # Use 'name' as the key
        jobs:
          - name: echo-job  # Use 'name' as the key
            tasks:
              - exec:
                  command: "echo"
                  arguments:
                    - "hello"
