pipelines:
  hello-pipeline:
    group: sample-group
    materials:
      git:
        url: 'https://github.com/Vinayaklondhe-hash/GOCD.git'
        branch: main
    stages:
      - hello-stage:
          jobs:
            - echo-job:
                tasks:
                  - exec:
                      command: echo
                      arguments:
                        - hello
