format_version: 3
name: sample-pipeline
group: sample-group
stages:
  - name: SampleStage
    jobs:
      - name: Job1
        tasks:
          - exec:
              command: "echo"
              arguments: ["Job1: This is Stage SampleStage"]
      - name: Job2
        tasks:
          - exec:
              command: "echo"
              arguments: ["Job2: This is Stage SampleStage"]
